[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  REACT_APP_API_URL = "http://13.59.76.17"
  REACT_APP_S3_URL = "https://wiating-dev.s3.eu-central-1.amazonaws.com"
  REACT_APP_AUTH_DOMAIN = "merito.eu.auth0.com"
  REACT_APP_AUTH_CLIENT = "IpMRzFHzBdQzKfGYqLOqo0XBtzc4SWee"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "http://13.59.76.17"
  REACT_APP_S3_URL = "https://wiating-dev.s3.eu-central-1.amazonaws.com"
  REACT_APP_AUTH_DOMAIN = "merito.eu.auth0.com"
  REACT_APP_AUTH_CLIENT = "IpMRzFHzBdQzKfGYqLOqo0XBtzc4SWee"
